### ISSUE TITLE
problem with making an audio file after finished all settings.

### ISSUE THREAD

**Issue by inamnk** [Zuntan03/EasyBertVits2#5]
こんにちは。

I'm a beginner studying AI with your program.
Thanks for making this great program.

I have a problem with making audio after finished all settings.
![missing](https://github.com/Zuntan03/EasyBertVits2/assets/171487533/dab979e1-6f30-4296-9924-fc5c22b785f5)
red lined area
and

06-02 20:59:48 INFO     | server_fastapi.py:298 | 127.0.0.1:14701/voice  model_id=12&speaker_name=JVNV-F2&sdp_ratio=0.2&noise=0.2&noisew=0.9&length=1&language=JP&auto_translate=false&auto_split=false&emotion=0 text=まだここにいたんですね。
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\iNa\Downloads\Bert-VITS2\server_fastapi.py", line 301, in voice
    return await _voice(
  File "C:\Users\iNa\Downloads\Bert-VITS2\server_fastapi.py", line 232, in _voice
    audio = infer(
  File "C:\Users\iNa\Downloads\Bert-VITS2\infer.py", line 227, in infer
    net_g.infer(
  File "C:\Users\iNa\Downloads\Bert-VITS2\models.py", line 1015, in infer
    x, m_p, logs_p, x_mask, _ = self.enc_p(
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\models.py", line 410, in forward
    x = self.encoder(x * x_mask, x_mask, g=g)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\attentions.py", line 112, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\attentions.py", line 264, in forward
    q = self.conv_q(x)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\iNa\Downloads\Bert-VITS2\venv\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 192, 47, 47]

after pressed 生産音頻 button, still there is no audio control panel, also didn't make any of audio file.
maybe is this problem of web browser or java something else?

thank you for reading this.

**Comment by MahuaGit** [comment]
Excuse me, have you already solved this? I got the same problem.
